[build]
  base = "consumer-website"
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_API_URL = "http://localhost:5000/api"
  NEXT_PUBLIC_BACKEND_URL = "http://localhost:5000"