services:
  - type: web
    name: gold-shopy
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: USE_MOCK_DB
        value: false
      - key: MONGODB_URI
        value: mongodb+srv://Gold-shop:${MONGODB_PASSWORD}@cluster0.ela5ylc.mongodb.net/goldshop?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: goldshopsecret
      - key: PORT
        value: 10000